name: 'kubectl deployment action'
description: 'Use kubectl for controlling your clusters'
branding:
  icon: terminal
  color: blue
inputs:
  kubectl-version:
    description: Version of kubectl to use
    required: false
    default: latest
  kube-config:
    description: A base64 encoded reference to your authorization file (~/.kube/config)
    required: true
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
  