name: 'kubectl deployment action'
description: 'Use kubectl for controlling your clusters'
branding:
  icon: terminal
  color: blue
inputs:
  kubectl-version:
    description: Version of kubectl to use
    required: true
  kube-config:
    description: A base64 encoded reference to your authorization file (~/.kube/config)
    required: false
runs:
  using: 'node18'
  main: 'index.js'
